### ISSUE TITLE
Enhancement : Add a shortcut to go back to the list

### ISSUE THREAD

**Issue by athimel** [ncarlier/readflow#10]
I use "Enter" to open an article, "M" to mark it as read.

I don't think there's a shortcul to go back to the list I if don't want the article to be marked as read

**Comment by ncarlier** [comment]
You can use [backspace].
You can type [?] to see all shortcuts.

**Comment by athimel** [comment]
[backspace] doesn't bring me back tonthe list but on the page before.

But If didn't try [?], I'll do it next time

**Comment by athimel** [comment]
I confirm that [backspace] brings me back to the page after the list.

You can see it with :

1. Open a category
1. Open an article
1. Press [backspace]

You will be redirected to the list indeed but you will be in "unread" page, where you should stay on the selected category

**Comment by ncarlier** [comment]
Sorry, but I can't reproduce the pb. If I follow the steps, I return to the category page as expected.
