### ISSUE TITLE
Add a bookmarklet to add an article quickly

### ISSUE THREAD

**Issue by dolanor** [ncarlier/readflow#11]
Hi!
Nice project! I've had a similar idea since I've read about 1flow a few years ago.
It's very interesting as many webpages that I fav'ed back in the day don't exist anymore. I lost all reference and content. web.archive.org exists of course, but it's not failsafe.
Anyway, in the settings, can we have some bookmarklet button, so we could add anything while we're browsing?

**Comment by ncarlier** [comment]
Hi! 
You can find here the documentation about bookmarklets: https://about.readflow.app/docs/en/read-flow/bookmarklet/

**Comment by dolanor** [comment]
Ok, found it! https://readflow.app/settings/api-keys
It wasn't so obvious to me, and I guess I didn't look for it enough. It was more obvious on keeper.
Thank you!
