### ISSUE TITLE
icons on the mobile view

### ISSUE THREAD

**Issue by nlehuby** [ncarlier/readflow#12]
The icons do not show up on my mobile phone, the labels are used instead, which is quite unusable :disappointed: 

Firefox 68.1, no additional modules, Android 7.1.1

![image](https://user-images.githubusercontent.com/919962/64366988-a1ddbe80-d017-11e9-98a5-889748fb43ad.png)

**Comment by ncarlier** [comment]
Fonts are loaded from Google CDN: https://fonts.googleapis.com/icon?family=Material+Icons
Can you try a direct access to this URL?
It's maybe related to a blocker installed on your FF?
Tested OK on Android 9 with Firefox 68.1.

**Comment by ncarlier** [comment]
Issue reproduced \o/
Can you turn on webfonts in FF? Basically, do the opposite of this: https://support.mozilla.org/en-US/kb/turn-web-fonts-firefox-android

**Comment by nlehuby** [comment]
indeed it works with webfonts turned on :+1:

**Comment by ncarlier** [comment]
Great!
