### ISSUE TITLE
processor.go:17:13: undefined: expr.Node

### ISSUE THREAD

**Issue by sevospl** [ncarlier/readflow#16]
```
github.com/ncarlier/readflow/pkg/rule-engine
# github.com/ncarlier/readflow/pkg/rule-engine
go/src/github.com/ncarlier/readflow/pkg/rule-engine/processor.go:17:13: undefined: expr.Node
```
FreeBSD 11, amd64. Any idea as to what's the issue?

**Comment by sevospl** [comment]
This issue seems to occur on my PC in the Alpine Linux subsystem as well.

**Comment by ncarlier** [comment]
Your version of Go may be below 1.11
If you are using Go 1.11 you have to enable Go Modules: `export GO111MODULE=on`

**Comment by sevospl** [comment]
> Your version of Go may be below 1.11
> If you are using Go 1.11 you have to enable Go Modules: `export GO111MODULE=on`

I'm using the latest Go version, so it's not that. :(

**Comment by ncarlier** [comment]
Can you try `go mod verify` in order to verify dependencies?

**Comment by sevospl** [comment]
```
[sevos]:<~>$ go mod verify
go: cannot find main module; see 'go help modules'
```

**Comment by ncarlier** [comment]
Oh! you are using `go get` and not building from source. Ok.
Then can you retry the go get but after `export GO111MODULE=on`?

**Comment by sevospl** [comment]
> Oh! you are using `go get` and not building from source. Ok.
> Then can you retry the go get but after `export GO111MODULE=on`?

Ah, yes. I just figured out that I should verify it in the repo folder. However, it worked. :) I guess Readflow is not yet compatible with Go 1.13?

**Comment by ncarlier** [comment]
Readflow support Go 1.13: https://github.com/ncarlier/readflow/blob/master/go.mod#L29
Go 1.13 should use GO111MODULE=auto by default. Maybe I miss something but I don't know what : https://github.com/golang/go/wiki/Modules#recent-changes

**Comment by sevospl** [comment]
I see! As this issue is resolved, I'm going to close it. Thanks for your help :)
