### ISSUE TITLE
The easiest way for auth without 3rd party OAuth service?

### ISSUE THREAD

**Issue by sevospl** [ncarlier/readflow#18]
I haven't started getting Readflow running up yet, however I noticed that it uses 3rd party OAuth which is something I'd like to avoid. What's the easiest way to replace it with something local? 

"mock", "proxy" or OIDC if URL - not quite sure what they mean...

**Comment by ncarlier** [comment]
If you define a proxy, readflow will expect a special HTTP header (X-WEBAUTH-USER or X-Auth-Username) to define the connected user.

This is a classic method used when you place a reverse proxy in front of your application.
You can use Apache httpd, NGINX, Traefik, Kong, etc. to configure your authentication method and then pass the username in this header.

Here how to proceed with Traefik: https://docs.traefik.io/middlewares/basicauth (Check [headerField](https://docs.traefik.io/middlewares/basicauth/#headerfield) section for details).
