### ISSUE TITLE
Redirect to about.readflow.app

### ISSUE THREAD

**Issue by cur1ou5soul** [ncarlier/readflow#19]
Hi, 

first of all great work! :-) 

I wanted to make readflow work out of a Docker-Compose with traefik. After Setting the env vars - if I go to my domain. I get redirected to about.readflow.app. 

Could you please give me a hint? 

regards,

**Comment by ncarlier** [comment]
Hi,

It's located here: https://github.com/ncarlier/readflow/blob/master/ui/src/index.tsx#L26

If this is your first visit, you will be redirected to the "about" site.
You can bypass this behavior by pointing directly to `/login`.
This will trigger the login redirection and then create a cookie to avoid the first time visit redirection.

Regards

**Comment by cur1ou5soul** [comment]
thx for your fast response maybe I just didn't get it right. Know the app is complaining about my redirect uri.

**Comment by ncarlier** [comment]
What kind of complaint?

**Comment by cazzoo** [comment]
Hi @ncarlier,
I'm currently trying to deploy the stack in docker swarm.
So far I have good success, but I'm facing the same issue than atomicwrites.
I did set the READFLOW_PUBLIC_URL env variable but still I get redirected to the about.readflow.app page.

Any advice?

**Comment by cazzoo** [comment]
Ok nevermind, as suggested above I work that around modifying the constants manually and building the image. Strange behaviour that the webserver doesn't take ENV variables when providing...
BTW I have another question regarding oidc. I can see the TS oidc library has been archived and couldn't figure to find a good alternative. 
Anyway, I'm trying to configure Authy to allow OIDC, but I cannot find any CLIENT_SECRET param.
I assume then it should be considered as "public" so I updated my auth provider to do public auth but I'm always getting :
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."}
```
While my setup is defining this:
```
redirect_uris:
          - https://flow.mydomain.com/signin-callback.html?redirect=https://flow.mydomain.com/login
          - https://flow.mydomain.com/login
          - https://flow.mydomain.com/signin-callback.html?Fredirect=https%253A%252F%252Fflow.mydomain.com%252Flogin
```

**Comment by ncarlier** [comment]
Hi,
the UI is just a static website and the configuration can only be done during the build phase.
We could imagine a configuration API to make this configuration dynamic. But for now, it is hard-coded during the build phase.

The status of the OIDC client library is a big issue. So far, I only have two leads: Keycloak JS adapter or https://github.com/openid/AppAuth-JS but with some tricks.

Regarding your redirect_uri configuration you should try:
- `https://flow.mydomain.com/signin-callback.html` (without query parameters)
or
- `https://flow.mydomain.com/*` (if wildcard is supported by your provider?)

**Comment by cazzoo** [comment]
Ok I got progress, as I thought it was an Auth server configuration issue.
Now I can get authorisation form, but when approving It's stuck on signin-callback.html (No code in response).
![image](https://user-images.githubusercontent.com/1876754/146783288-209dd6fb-b450-47ed-9371-51da227b0c5d.png)
Despite the code has been provided in the response...
![image](https://user-images.githubusercontent.com/1876754/146783656-58dcc211-4e65-4d8b-bc70-59686170f2ba.png)

Should redirect_url redirect to <host>/login or just root?

**Comment by ncarlier** [comment]
/login is used to trigger the authentication.
If you have never been authenticated before (no `readflow.lastRun` local storage key), the UI redirect you to the configured redirection URI ("about page" for the hosted platform or `/login` for self hosted platform).

Here I suspect a CORS issue. Can you check your browser logs (development console) and see if a more explicit error was logged.

**Comment by cazzoo** [comment]
I sorted the CORS issue already, currently allowing * for any origin.
Full network stack doesn't show CORS issue (not auth provider logs):
![image](https://user-images.githubusercontent.com/1876754/146799825-4d4eb767-ef02-4eda-aa20-54d0df88c9d3.png)
This is my IAM middleware configuration : 
![image](https://user-images.githubusercontent.com/1876754/146798726-5b80a174-78f4-4063-82b7-a688ad104591.png)

I've been breaking into the lib and I don't understand some things, maybe you have an idea:
![image](https://user-images.githubusercontent.com/1876754/146799443-3bd43640-1f27-4af1-ac11-e3b453063d86.png)

**Comment by ncarlier** [comment]
Have you see this issue: https://github.com/IdentityModel/oidc-client-js/issues/967 ?
Can you try to edit https://github.com/ncarlier/readflow/blob/master/ui/public/signin-callback.html#L58 inside the docker container and retry?

**Comment by ncarlier** [comment]
Maybe an important detail is that the OIDC request use `response_type: 'code'` (https://github.com/ncarlier/readflow/blob/master/ui/src/auth/OIDCAuthService.ts#L17) and expect that the flow is `Authorization Code with PKCE` because it's a public client.

**Comment by cazzoo** [comment]
The Authelia Provider is configured to serve "code" as default.
I did pass `{ response_mode: "query" }` in UserManager method and I faced some other CORS issues. I had to allow `authorization` header.
Now I can get into readflow but I have some other issues:
GraphQL complains about `ServerParseError Unexpected token < in JSON at position 0` and UI displays the following:
![image](https://user-images.githubusercontent.com/1876754/146811108-ea28cfc4-0cd6-4b9a-ad73-63d1c626dea5.png)

I suspect user not created in readflow with the current flow?

**Comment by cazzoo** [comment]
Well, I figured that I missed several CORS attributes for my request to reach the API server.
For the sake of everyone, here's a list of required attributes:
```
accesscontrolallowmethods: GET, POST, PUT, DELETE, PATCH, HEAD
ccesscontrolallowheaders: Accept, Content-Type, Content-Length, Accept-Encoding, Authorization
accesscontrolalloworiginlist: '*' // or your APP origin
```

Now, It's not a 405 anymore I receive but a 401, telling:
`token contains an invalid number of segments`

From now on, I feel the token provided to the API misses some bits but I don't know exactly what it misses.

**Comment by ncarlier** [comment]
This kind of error is returned when the token has less than 3 parts. Can you give a access token example?

**Comment by cazzoo** [comment]
I believe the token has been somehow truncated, here is the authorization header:
`Bearer vSDKXk_vABQFOGQSgg0XfiMtgtjzu6fR8-axmmxfo6o.IHzJ005MvJJ80dytBRBwRNBABWibE-Uhef_EHMpb2L0`

I'm used about JKS tokens but the OAuth token seems completely different. I cannot see any "." in it...

**Comment by ncarlier** [comment]
Indeed, the jwt is valid and should be accepted. But I don't understand why you get a truncated token? The server only accept jwt and not oauth obfuscated token.

**Comment by cazzoo** [comment]
I'm not sure it is related but I've seen that jwt-go has been deprecated as well due to originator not in position to continue working on it. It's successor is https://github.com/golang-jwt/jwt.
While digging into the lib, I found the same error message: `token contains an invalid number of segments`
I will try to get your code with the latest lib to see if it unlocks the situation (maybe this is something you already worked on?).

**Comment by ncarlier** [comment]
Thanks for spotting this deprecation. I will upgrade the JWT lib tonight.
Just to be sure, when you open the developer console, is the JWT inside the `Authorization` header correct (readable using [jwt.io](https://jwt.io/))?
If so, does the `kid` claim in the header refer to an existing key in your JWKS URI? (ex: https://login.nunux.org/auth/realms/readflow/protocol/openid-connect/certs for readflow's OIDC official provider)
This JWKS URI must be provided the [.well-known/openid-configuration](https://login.nunux.org/auth/realms/readflow/.well-known/openid-configuration) endpoint of your OIDC provider (`jwks_uri` attribute).

**Comment by cazzoo** [comment]
I have no KID claim in the JWKS URI. I can see several people complaining the same using Authelia [1979]https://github.com/authelia/authelia/issues/1979) & [189](https://github.com/authelia/authelia/issues/189).
Probably I need to check on this side now.

**Comment by cazzoo** [comment]
I decided to tests the flow by myself, trying to post the request using insomnia (or postman/curl) and when passing the whole request to the API server using the JWT token I can get a response from the server.
Definitely I can see in the network panel of debugger that the token passed by is the auth_token and not the id_token... This is definitely the reason why it doesn't work.
What I don't know now, is how to make sure the id_token is being used instead of auth_token by the client...

**Comment by ncarlier** [comment]
Authelia seems to have a beta support of OIDC: https://www.authelia.com/docs/configuration/identity-providers/oidc.html and don't support [RFC9068](https://datatracker.ietf.org/doc/html/rfc9068) for its access_token. Readflow use JWT access_token in order to verify the token autonomously (without calling the auth server).
I think you should give a try to the [authentication with a proxy](https://github.com/ncarlier/readflow/blob/master/etc/default/readflow.env#L7). If you are using Traefik with Authelia you can use the [forwardauth](https://doc.traefik.io/traefik/middlewares/http/forwardauth/#authresponseheaders) plugin to make everything work together.

**Comment by cazzoo** [comment]
Indeed, you're pointing exactly where the bit misses...
I was attempting to get it working anyway, it would have been good addition for Readflow to get it working with access_token.
BTW I will fallback to standard forwardauth. Definitely Traefik can handle it

**Comment by cazzoo** [comment]
Hmmm I think i'm lost now... I've switched to proxy mode, but still get weird reaquest payload when graphql is being queried...
```
{variables: {},…}
query: "{\n  me {\n    username\n    hash\n    hashid\n    plan\n    customer_id\n    last_login_at\n    created_at\n    __typename\n  }\n}\n"
variables: {}
```
All HTTP queries passes but still I get:
![image](https://user-images.githubusercontent.com/1876754/147162751-46d775d3-e938-4206-9f04-3668c5b7966b.png)
