### ISSUE TITLE
'Mark all as read' raises an effort even when successful

### ISSUE THREAD

**Issue by athimel** [ncarlier/readflow#21]
I have a category when N articles.
When I use the "Mark all as read" button I have the following error : « User Error: expected iterable, but did not find one for field Mutation.markAllArticlesAsRead. » in the modal.
Please find attached a screenshot : ![Screenshot_20200501-230641__01](https://user-images.githubusercontent.com/1804382/80842812-e2232a00-8c02-11ea-9534-56b3f56a9a21.jpg)

By the way, the N articles are actually marked as read.

**Comment by ncarlier** [comment]
Fixed. Thanks for the report.
