### ISSUE TITLE
Priority weights and ordering based on that

### ISSUE THREAD

**Issue by Skarlso** [ncarlier/readflow#25]
Hi!

Fantastic app, love it, about to install it. :)

I was wondering if you would be willing to add something like define a weight on an article, how important it is to be read, and then have a priority view where it would show you the list of articles in order of weight / priority.

Cheers,
Gergely.

**Comment by ncarlier** [comment]
Hi Gergely,

it's something definitely planned. But I'm still wondering how to implement this.

For incoming articles, ideally I would like to do it dynamically. Extract keywords and themes from content and compare theme with an user-defined list of interests. Like a recommendation engine. The articles would thus have a weight and we would have a new section in the UI to see potentially interesting articles. 
Regarding starred articles it should be something manual. The ability to put a weigth on an article. Far more simple ;)

Right now I'm working on the ability to save a standalone copy of an article (on local machine but also on remote S3 bucket). As soon it's over I will certainly work on ordering starred articles.

**Comment by ncarlier** [comment]
You can now give more than one star to an article and sort them according to the number of stars.

**Comment by Skarlso** [comment]
Super amazing! Thanks very much!!
