### ISSUE TITLE
Enhancement : save the ordering condition

### ISSUE THREAD

**Issue by athimel** [ncarlier/readflow#3]
I use to read my articles in order from most recent to oldest.

But the default order is from oldest to most recent.

Each time I access readflow, I have to invert the ordering condition. I would by great if this setup could be saved.

Cherry on the cake : keep a different ordering condition per category ;)

**Comment by ncarlier** [comment]
A good start for a "user preferences" panel in the configuration page:
Allows the user to choose the default order.

The cherry may be too expensive ;)

**Comment by ncarlier** [comment]
Fixed.

(cherry on the cake included)
