### ISSUE TITLE
Migration issue in docker image

### ISSUE THREAD

**Issue by Michaelpalacce** [ncarlier/readflow#39]
Trying to run readflow with docker but I am getting the following error:

{"level":"warn","version":1,"time":1641044388,"message":"Migrating Database..."}
{"level":"warn","version":2,"time":1641044391,"message":"Migrating Database..."}
{"level":"warn","version":3,"time":1641044392,"message":"Migrating Database..."}
{"level":"warn","version":4,"time":1641044393,"message":"Migrating Database..."}
{"level":"warn","version":5,"time":1641044393,"message":"Migrating Database..."}
{"level":"warn","version":6,"time":1641044393,"message":"Migrating Database..."}
{"level":"warn","version":7,"time":1641044393,"message":"Migrating Database..."}
{"level":"warn","version":8,"time":1641044394,"message":"Migrating Database..."}
{"level":"warn","version":9,"time":1641044394,"message":"Migrating Database..."}
{"level":"warn","version":10,"time":1641044394,"message":"Migrating Database..."}
{"level":"fatal","error":"pq: syntax error at or near \"VALUE\"","time":1641044394,"message":"Unable to apply migration"}

**Comment by ncarlier** [comment]
Wich version of PostgreSQL are you using?

**Comment by Michaelpalacce** [comment]
9...I just realized you are targeting 14+, maybe add this as a requirement?

**Comment by ncarlier** [comment]
PostgreSQL 9 is no more supported. Readflow should work fine with PosgreSQL 10 to 14.
