### ISSUE TITLE
Ordering condition makes inconsistent 'unread' count

### ISSUE THREAD

**Issue by athimel** [ncarlier/readflow#4]
Here is my use case :

1. Open readflow : I have 182 articles to read ![1](https://user-images.githubusercontent.com/1804382/57620648-acb4a500-7589-11e9-9b0b-f82c2323752e.png)
1. Invert order to get newest articles first : I still have 182 articles to read ![2](https://user-images.githubusercontent.com/1804382/57620683-c81fb000-7589-11e9-8768-c72d0de1371a.png)
1. Open the any article (Here I take the first one) ![4](https://user-images.githubusercontent.com/1804382/57620719-e8e80580-7589-11e9-9723-bbb38fdefac7.png)
1. Mark as read

I'm redirected to the list of articles (which is fine) but :
- the ordering condition is not kept (I should have newest first) 
- the unread count is not decreased, I still have 182 articles to read (I should have 181)

![5](https://user-images.githubusercontent.com/1804382/57620828-382e3600-758a-11e9-83f7-25c41ec72a74.png)

By the way, if I invert the ordering condition, I get the correct unread count (181) and the article is gone !

![6](https://user-images.githubusercontent.com/1804382/57620876-58f68b80-758a-11e9-96bf-b2952f4b9575.png)

**Comment by ncarlier** [comment]
Fixed. Is it ok for you?

**Comment by athimel** [comment]
Perfect, thanks!
