### ISSUE TITLE
Feature request：Support for various web styles 

### ISSUE THREAD

**Issue by NoverNobida** [ncarlier/readflow#40]
If various web page styles(or markdown styles) are supported, the reading experience will be improved. Now these styles are not obvious and beautiful. Such as
1. Blockquotes
    > quotes
2. Inline code
    `code`
3. Code Blocks
    ```
    code
    code
    ```

**Comment by ncarlier** [comment]
Thanks for the issue. I have updated the style to improve this. Let me know if it's more readable.

**Comment by NoverNobida** [comment]
It's pretty good now, and the reading experience is good.
But whether to consider saving the image on the server? Because sometimes webpages or articles would be deleted before reading, or I want to keep an article or webpage permanently, but the source webpage is deleted, images cannot be viewed.

**Comment by ncarlier** [comment]
Saving images directly to readflow would be cumbersome and should be a per article option.

For the moment, you have these options:
- put the article offline (the images are embedded in the content)
- download the article with the images (embedded or as a zip file)
- send the article to a archiving service (pocket, Nunux Keeper, ...) or to a S3 bucket (zipped or with embedded images)

I am looking for a solution to sync offline storage between devices. Via P2P or a central service. This could also be a great solution.

Another option could be to have a (T)LRU cache to manage the images of starred articles (such as Pocket).
