### ISSUE TITLE
How do you deploy this?

### ISSUE THREAD

**Issue by typkrft** [ncarlier/readflow#44]
```
❯❯❯ go get -v github.com/ncarlier/readflow
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

❯❯❯ curl -sf https://gobinaries.com/ncarlier/readflow | sh
  Error: Repository has no tags

❯❯❯ curl -s https://raw.githubusercontent.com/ncarlier/readflow/master/install.sh | bash
bash: line 7: ${os,,}: bad substitution
error: Unable to extract artefact URL

❯❯❯ sudo docker run -d --name=readflow ncarlier/readflow
Unable to find image 'ncarlier/readflow:latest' locally
docker: Error response from daemon: manifest for ncarlier/readflow:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

```

**Comment by ncarlier** [comment]
My bad, I just copied the process from my other projects and redflow is the only one without any tag and release. So curl and docker with the latest version can't work.

You have two options:

- Using `go get github.com/ncarlier/readflow` (should work... what is your Go version?)
- Using edge Docker image: `docker run ncarlier/readflow:edge`
 
I will delete the curl example until I publish a version.

**Comment by typkrft** [comment]
No worries. Go `go version go1.18 darwin/arm64`. This is probably my fault I think it was inadvertently installed from brew, normally I manage it with asdf pinned at an earlier release. So maybe too new or some other weirdness. Looking forward to giving it try. I also should have looked at the tags on docker hub. All the best!
