### ISSUE TITLE
get -v github.com/ncarlier/readflow results in pkg/model/category.go:55:42: undefined: gofakeit.RandString

### ISSUE THREAD

**Issue by user9931** [ncarlier/readflow#47]
Just want  to try the app. 
 curl -sf https://gobinaries.com/ncarlier/readflow | sh gives 

  Error: Repository has no tags

 go get -v github.com/ncarlier/readflow gives error

```
github.com/ncarlier/readflow (download)
github.com/ncarlier/readflow/pkg/model
# github.com/ncarlier/readflow/pkg/model
../../go/src/github.com/ncarlier/readflow/pkg/model/category.go:55:42: undefined: gofakeit.RandString
```
 go version
`go version go1.18.3 linux/amd64` and  _go env -w GO111MODULE=auto_ in ~/.profile if it matters

**Comment by ncarlier** [comment]
You can install readflow using Golang with this cmd:

```bash
go install -v github.com/ncarlier/readflow@latest
```

I updated the README.
