### ISSUE TITLE
Enhancement : Notify the user when new articles are available

### ISSUE THREAD

**Issue by athimel** [ncarlier/readflow#5]
Most of the time, I let opened readflow on a list of articles. I could be interesting to be notified when new articles are available and I shall refresh

**Comment by ncarlier** [comment]
Have you try notifications? https://about.readflow.app/docs/en/read-flow/notifications/

**Comment by athimel** [comment]
This is personal but I don't really like real-time notifications, because they interrupt me in my work.

I just enabled notifications on readflow, I'll see and tell you what I think about it - even if I think I'd prefer asynchronous notifications (aka "I see them when I go to readflow") -.

**Comment by ncarlier** [comment]
Proposal:
When new items are availablea, a button labeled "View X new items" is displayed at the top of the acticve page.

Using silent notification can be an option.
Another option can be a GraphQL subscription.

**Comment by athimel** [comment]
I don't know about GraphQL subscriptions, but the button labeled "View X new items" would be great for me
