### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ajtatum** [ncarlier/readflow#50]
Hi, this app looks amazing but when I try to install it via Go or using the curl methods, it gives errors such as "Unable to extract artefact URL". I'm also planning to try out feedpushr and noticed that the instructions where slightly different by supplying a version and that repo has releases/packages.

**Comment by ajtatum** [comment]
Docker also gives the error "docker: Error response from daemon: manifest for ncarlier/readflow:latest not found: manifest unknown: manifest unknown."

**Comment by ncarlier** [comment]
Hi, thank you for your interest.
Yes this project is still maintained but its packaging is a bit messy. Unlike Feedpushr this project does not yet have a tag. This is the only reason why all installation methods are broken (`go get`, `curl` and docker "latest").
Despite the fact that the current project is quite usable and stable I still have a feature backlog that I want to add before releasing the first "1.0". It's still a "beta".
Until this long awaited 1.0 you can either build the project (`git clone` following by `make`) or use the unstable Docker image: https://hub.docker.com/r/ncarlier/readflow/tags
For the moment you also have to build the UI separately (another little thing into the backlog 😉) : https://github.com/ncarlier/readflow/tree/master/ui

**Comment by ajtatum** [comment]
Awesome, glad to hear as this actually looks (IMO) as the best self hosted reader and something that I'd actually ditch Inoreader for. I've tried a lot of self-hosted RSS readers, and they either lack the features I like (like webhooks) or they're, well, not too great looking. So, I'm glad to hear that this is still a WIP and I totally get it. Between both of your projects, they appear to be things I've been hunting for... for quite some time... with Feedpushr it's more so that I'd have change some infrastructure around to get it working.

Anyway, would the result of using your [Docker compose](https://github.com/ncarlier/readflow/blob/master/docker-compose.yml) file work, but instead of using the latest tag and switching it to "edge" be the same as manually cloning/making the project? (In regards to just your project.)

**Comment by ncarlier** [comment]
Yes. You can remove the build part (https://github.com/ncarlier/readflow/blob/master/docker-compose.yml#L59) and switch to the `edge` version (image: "ncarlier/readflow:edge"). This should work. But you still have to build the UI Docker image (https://github.com/ncarlier/readflow/blob/master/docker-compose.yml#L78).

**Comment by ncarlier** [comment]
For your information, self-hosting installation has been reviewed and simplified. UI is now part of the official Docker image.
