### ISSUE TITLE
All suggested installation methods fail on Ubuntu 20.04

### ISSUE THREAD

**Issue by Almost-Senseless-Coder** [ncarlier/readflow#51]
All suggested installation methods fail on Ubuntu 20.04 server edition.

**Curl**: Error: Failed to extract resource URL (the same happens if I run `install.sh` from my terminal after cloning the repository).

**gobinaries.com**: Error: The repository has no tags.

**docker**: The container exits on run with error code 1.

Haven't tried build from source yet, as I didn't really plan to install Golang on my server...

**Comment by ncarlier** [comment]
Hi,

Curl examples will work as soon the project will be have a TAG. It's still a "beta".

With Docker you have to provide the PostgreSQL connection string.

```bash
$ docker run -it --rm \
    -p 8080:8080 \
    -e READFLOW_DB=<YOUR POSTGRESQL CONNECTION STRING> \
    ncarlier/readflow:edge
```

**Comment by Almost-Senseless-Coder** [comment]
Thanks, that solves it ^^
