### ISSUE TITLE
Focus lost because of a new article coming in

### ISSUE THREAD

**Issue by athimel** [ncarlier/readflow#6]
I was reading some articles and marking them as read using the "M" key.

One article came on top of the list (I'm using the "newset first" order).

As soon as this article appeared, it became impossible to mark the first article as read using the "M" key.
NB : I can still mark articles as read using the button.

Once this new article as been marked as read (using the button), I can use again the "M" key

**Comment by ncarlier** [comment]
Fixed. Is it ok for you?

**Comment by athimel** [comment]
I'll try to test it, but I can't anticipate when new articles will come in :)
