### ISSUE TITLE
Commands from readme.md to retrieve binaries do not work

### ISSUE THREAD

**Issue by jeffcutsinger** [ncarlier/readflow#61]
```
curl -sf https://gobinaries.com/ncarlier/readflow | sh
```

results in

```
Error: Repository has no tags
```

and

```
curl -s https://raw.githubusercontent.com/ncarlier/readflow/master/install.sh | bash
```

results in

```
error: Unable to extract artefact URL
```

The repository does indeed have no tags, and looking at install.sh, it seems to assume there will be GH releases, which I'm not seeing either.

**Comment by ncarlier** [comment]
Thi project is finally tagged. Binary retrieval should work as expected.
