### ISSUE TITLE
[BUG] always redirect to info endpoint

### ISSUE THREAD

**Issue by greggameplayer** [ncarlier/readflow#65]
Hello,

There seems to be a problem,

I've put the container from docker hub onto my kubernetes and when i want to access url, it always redirect me to the info endpoint and so i can't access the ui.

Can you fix this please ?

**Comment by ncarlier** [comment]
Can you set this variable like this:
```bash
export READFLOW_UI_DIRECTORY=/var/local/html
```

**Comment by greggameplayer** [comment]
i get a 404 page not found

**Comment by greggameplayer** [comment]
here is the current log : 
![image](https://github.com/ncarlier/readflow/assets/33609333/d487dd47-9941-4ae2-9de7-81591f7728f8)

**Comment by greggameplayer** [comment]
and for information i've set all those env variables : 
![image](https://github.com/ncarlier/readflow/assets/33609333/47247b00-b28f-4de5-9b1b-74be31a12156)

**Comment by greggameplayer** [comment]
okay it's good it was because i was overriding the folder /var/local using a volume to pass the auth htpasswd secret so now it's good but there is another problem, the htpasswd doesn't work (it doesn't allow me to login) using the standard format generated by the htpasswd command

**Comment by ncarlier** [comment]
Do you use bcrypt as encryption method?
``` bash
htpasswd -B -c .htpasswd test
```

**Comment by greggameplayer** [comment]
no i've not used the -B parameter, i will try with it

**Comment by greggameplayer** [comment]
ok it's good with that, maybe it will be good to add that to the documentation 😄
