### ISSUE TITLE
Can't build UI

### ISSUE THREAD

**Issue by maksalees** [ncarlier/readflow#66]
When I try to build the UI with `npm run build`, the following error appears:
```
> readflow-app@0.1.0 build
> npm run lint && react-scripts build


> readflow-app@0.1.0 lint
> eslint src/**/*.{js,jsx,ts,tsx,json}


Oops! Something went wrong! :(

ESLint: 8.25.0

No files matching the pattern "src/**/*.jsx" were found.
Please check for typing mistakes in the pattern.
```

**Comment by maksalees** [comment]
Any progress?

**Comment by ncarlier** [comment]
Hi, I am confused because I am unable to reproduce your issue. Can you retry on a fresh clone using the `make ui` command?

```bash
git clone git@github.com:ncarlier/readflow.git
cd readflow
git submodule init && git submodule update
make ui
```

**Comment by ncarlier** [comment]
Maybe related to your issue : https://oss.issuehunt.io/r/manuelbieh/react-ssr-setup/issues/88

**Comment by maksalees** [comment]
> Hi, I am confused because I am unable to reproduce your issue. Can you retry on a fresh clone using the `make ui` command?
> 
> ```shell
> git clone git@github.com:ncarlier/readflow.git
> cd readflow
> git submodule init && git submodule update
> make ui
> ```

Still same issue
```
make: go: No such file or directory
>>> Building Web UI...

> readflow-app@0.1.0 build
> npm run lint && react-scripts build


> readflow-app@0.1.0 lint
> eslint src/**/*.{js,jsx,ts,tsx,json}


Oops! Something went wrong! :(

ESLint: 8.25.0

No files matching the pattern "src/**/*.jsx" were found.
Please check for typing mistakes in the pattern.

make: *** [Makefile:132: ui] Error 2
```

**Comment by maksalees** [comment]
> Maybe related to your issue : https://oss.issuehunt.io/r/manuelbieh/react-ssr-setup/issues/88

After I replaced `eslint src/**/*.{js,jsx,ts,tsx}` to `eslint --ext .js,.jsx,.ts,.tsx src/` in `ui/package.json`, it works. I will create a pull request with a fix.
