### ISSUE TITLE
Document OIDC variables

### ISSUE THREAD

**Issue by mpldr** [ncarlier/readflow#69]
OIDC requires a ClientID and in some cases a Client Secret to be set. The example config does not make clear how these can be set. A glance at the code seems to indicate that these have to be set at compile time. Is that correct? If so, could this be changed in order to allow for easier container deployment?

**Comment by ncarlier** [comment]
Hi, you are right: it is set during the build time: see `REACT_APP_CLIENT_ID` configuration variable on the [README page](https://github.com/ncarlier/readflow/tree/master/ui).
But it's true this should be more dynamic. I will try to improve this. Using Docker I can try to create a specific entrypoint managing this.

**Comment by ncarlier** [comment]
With the last update you can configure the client_id at runtime using [this configuration](https://github.com/ncarlier/readflow/blob/master/pkg/config/defaults.toml#L83). This only works if the UI is served by the main process (https://github.com/ncarlier/readflow/blob/master/pkg/config/defaults.toml#L78).

**Comment by mpldr** [comment]
Thanks a bunch! Gave it a spin and there seems to be an issue with the processing of the provider URL. Invalid response Content-Type: `https://id.moritz.sh/application/o/readflow` is turned into `https://id.moritz.sh/application/o/readflow/ /.well-known/openid-configuration`

**Comment by mpldr** [comment]
Found the issue, it's in the generated config.js: 

```js
const __READFLOW_CONFIG__ = {
    // API base URL, default if empty
    // Values: URL (ex: `https://api.readflow.ap`)
    // Default: ''
    // Default can be overridden by setting ${REACT_APP_API_ROOT} env variable during build time
    apiBaseUrl: 'http://localhost:8080',
    // Authorithy, default if empty
    // Values: URL if using OIDC (ex: `https://accounts.readflow.app`), `none` otherwise
    // Default: `none`
    // Default can be overridden by setting ${REACT_APP_AUTHORITY} env variable during build time
    authority: ' https://id.moritz.sh/application/o/readflow/ ',
    // OpenID Connect client ID, default if empty
    // Values: string (ex: `232148523175444487@readflow.app`)
    // Default: ''
    // Default can be overridden by setting ${REACT_APP_CLIENT_ID} env variable during build time
    client_id: 'omitted',
}
```

The issue being rather obvious.

**Comment by mpldr** [comment]
Can confirm that login succeeds, but I have no idea what access token readflow is saving. It certainly isn't the ID token my identity server sent. It's significantly shorter and obviously corrupt, when trying to parse it.

**Comment by mpldr** [comment]
Looking at the frontend code, it also looks like it's trying to pass the access token, but the ID token is the one containing ID part of the OIDC. Not good with JS, so I might be misreading things here, though.

**Comment by ncarlier** [comment]
Sorry about the white space problem. I'll fix it.
Your access token is not corrupted but you have a "..." in the middle. This may be the result of a copy/paste from the Developer Console.
Regarding the cinematic: The frontend simply sends the access_token to the backend. The backend is expecting a JWT access_token. Its payload signature is validated. Its content is then decoded. The backend tries to extract the `email` or `preferred_username` claim (or falls back on the `ìss` claim) to use as the readflow username.
This is simple and efficient, but not suitable when using an opaque or "non-tunable" JWT access_token. To be more compliant, I should call the introspect endpoint to validate an opaque token, then swap the access token with an identification token to extract the username. But this will create a strong coupling with the authentication server and create an extra HTTP call for each API call (unless we add a cache or something).

**Comment by mpldr** [comment]
I got this token by clicking "Copy Value", which apparently truncated it… What the hell? You're correct. The full token got sent.

> The frontend simply sends the access_token to the backend. The backend is expecting a JWT access_token.

Yes, and per OIDC spec. The access_token isn't the one supposed to hold the username. That's the ID_Token (see example from [OIDC Spec](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse)). And falling back to the token issuer as the username doesn't really make sense either… shouldn't it be `sub`?

**Comment by ncarlier** [comment]
Last commit improve OIDC support. Username is fetched from multiple locations (JWT or introspection or User Info endpoint).
