### ISSUE TITLE
OIDC client_secret

### ISSUE THREAD

**Issue by maksalees** [ncarlier/readflow#71]
Some OIDC issuers require client_secret to be sent when logging in, but Readflow does not allow to specify it.

**Comment by ncarlier** [comment]
They shouldn't, because the user interface of readflow is a SPA (Single-Page Application) and therefore a public client. For a public client, client_secret makes no sense (https://oauth.net/2/client-types/). What is your OIDC provider?

**Comment by maksalees** [comment]
> They shouldn't, because the user interface of readflow is a SPA (Single-Page Application) and therefore a public client. For a public client, client_secret makes no sense (https://oauth.net/2/client-types/). What is your OIDC provider?

Sorry, I specified the client as public and now another problem has arisen. When trying to log in, Readflow error appears "token contains an invalid number of segments", then a redirect back to the OIDC provider, then again to this error. This happens forever. I use [Kanidm](https://kanidm.com) and it requires clients to support PKCE. It probably related to this. Does Readflow support PKCE?

**Comment by ncarlier** [comment]
Readflow support PKCE but expect a JWT access token. Is it possible to Kanidm to use a JWT instead of a random string?

**Comment by maksalees** [comment]
> Readflow support PKCE but expect a JWT access token. Is it possible to Kanidm to use a JWT instead of a random string?

No

**Comment by ncarlier** [comment]
Last commit improve OIDC support. Opaque OIDC token are supported.
