### ISSUE TITLE
readflow can't be installed on this device.

### ISSUE THREAD

**Issue by retarepo** [ncarlier/readflow#81]
Hello,

I recently stumbled over readflow and really like the project, but I need to admit, I have some troubles getting started. Most problems I already got over somehow and I plan to post here my compose file, which includes reverse proxy with trusted-proxy sso.

anyway, the following problem I can not get a handle on. I assume the "Installation" Box in the settings tab is for the PWA setup, right? however get on different devices the error: "Oh! readflow can't be installed on this device. Maybe your device is too old or the current readflow configuration does not allow it. Sad.". The devices are up to date and I can not find any configuration entries for this matter.

I tracked down the error message to [this file](https://github.com/ncarlier/readflow/blob/master/ui/src/settings/preferences/InstallationBox.tsx) and I need to admin, my typescript/react is a bit shabby: I understand that the switch block on line 59 is checking this, meaning `!!deferredPrompt` must be false, which is, without clicking anything equal to `window`, and there I am lost, is this some keyword in react/javascript or just something I fail to find in the code? I am also not sure what the double exclamation mark means.

Best wishes

**Comment by ncarlier** [comment]
Hello, thanks for the issue. The logic of the installation was a little shaky. Last commit should improve this. Regarding the double exclamation mark (!!) is generally used to ensure that the object is not empty, null or undefined.

**Comment by retarepo** [comment]
Hello and thank you for the quick response.

I pulled the latest docker image, which should include https://github.com/ncarlier/readflow/commit/7437f454de84be814d2a15e96692d3e4a62addcb

Unfortunately, the behavior hasn't changed and there is still nothing noticeable in the logs. In case it is relevant, I tried it with a Fairphone 4 (Fairphone OS, branded Android 13) using Firefox 130.0 and a Murena Teracube 2e (ElementOS, Android version 12) using /e/OS Browser 123.0. Any other information I could provide to help?

**Comment by retarepo** [comment]
I double checked with another app, and installing pwa works fine on my browser (via built-in menu), but readflow does not install as pwa for me.

I tested it with grocy on the same server, with the same setup (reverse proxy via traefik, and let's encrypt certs).

**Comment by retarepo** [comment]
Hello again, 

I found the problem and a workaround for my case. My instance is behind a reverse proxy with trusted header auth. After reading through the entire MDN about webapps I found the at https://developer.mozilla.org/en-US/docs/Web/Manifest the line:

> If the manifest requires credentials to fetch, the [crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) attribute must be set to use-credentials, even if the manifest file is in the same origin as the current page.

I didn't want to get into compiling readflow myself, so I added a bypass policy for the manifest in my authelia config and it works like a charm.

When I'm home I can test if the mentioned attribute in the link tag would help, as that would be a less wacky solution.

Best wishes!

**Comment by ncarlier** [comment]
Hello, thank you for the trouble shooting. This Manifest parameter is annoying because it depends on the installation. On readflow.app web assets are public and not behind an auth proxy. I wonder if we can set this parameter to "corossorigin" by default without affecting the "classic" installation mode?

**Comment by retarepo** [comment]
I'll check tonight or tomorrow if it would help at all. In that case you could just tie it to a config variable, or just use it, if auth is set to proxy. Let's see after my check.

**Comment by retarepo** [comment]
got a bit sidetracked, so only tested it now, and I am a bit lost with the compilation. I cloned this repo and the makefiles repo, and ran a docker build command. then I started it with my docker-compose file (changing the image tag to the one of the build command)... so far everything works and the app spins up. But now I tried changing the `ui/public/index.html` and compiled it again... yeah it still works, but nothing has changed. I refreshed the browser and still get the unchanged html header. Is there something I am missing? (I disabled cache on my browser for this)

**Comment by ncarlier** [comment]
It's a Progressive Web App. So you have to unregisterer the service worker to ensure that the cache is clear.

**Comment by retarepo** [comment]
thanks for the reply, I actually tried it on my mobile and on the desktop (ff for desktop doesn't support pwa, so i didnt expect there any "hidden" caches). Anyway, now it suddenly works (cache expired?!).

the result: Yes, changing the link to `<link rel="manifest" href="/manifest.json" crossorigin="use-credentials">` fixes the problem and I can install the PWA (on my phone) without the workaround at the proxy settings.

I do not know if this problem would apply for all setups with proxy auth, if that would be the case I would suggest to just tie it to the setting `READFLOW_AUTHN_METHOD=proxy`, otherwise you could just add an explicit setting, e.g., `READFLOW_PWA_CROSSORIGIN=true`. Either way, it would not affect any other setups.
