### ISSUE TITLE
Unable to read the bottom of an article on mobile

### ISSUE THREAD

**Issue by athimel** [ncarlier/readflow#9]
I cannot read the bottom if my article because of the "mark as read" button.

NB : of course, I cannot scroll down anymore

**Comment by athimel** [comment]
![Screenshot_20190514-083108](https://user-images.githubusercontent.com/1804382/57676249-619ba000-7624-11e9-9c49-7326d7c7d0d3.jpg)

**Comment by ncarlier** [comment]
Fixed. Is it ok for you?

**Comment by athimel** [comment]
Perfect, thanks!
